CREATE TABLE users (
  id INTEGER PRIMARY KEY IDENTITY(1,1) NOT NULL,
  name VARCHAR(50) NOT NULL,
  active BIT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT GETDATE(),
  updated_at DATETIME NOT NULL DEFAULT GETDATE()
);


